### ISSUE TITLE
Url-pattern

### ISSUE THREAD

**Issue by Adraas** [jfarr/spring-mvc-examples#2]
Hello. I write a my first project by the Spring Web MVC framework. For example, I use your project `spring-mvc-examples`. I read the documentation on the framework and saw how it uses the url-pattern `/*`, but you use the url-pattern `*.form`. The fact is that in my case also works only your option, but I couldn't find what it meant anywhere.

**Comment by jfarr** [comment]
Hi @Adraas, sorry but I wrote this code a long time ago and haven't looked at it in a long time. The choice of `*.form` for the url-pattern was pretty arbitrary. These days you typically wouldn't have to manually configure DispatcherServlet in web.xml anyway and you'd map all of your URI paths with `@RequestMapping`. I'd suggest checking out Spring Boot for a more modern way of building Spring applications. To be honest, I created this project mostly as a way for me to remember which versions of the various libraries (Spring, Hibernate, etc.) actually work together, back before Spring Boot was a thing. I hope a few people have found it somewhat useful over the years but I think I'm going to archive the project now since it's so drastically out of date.
